#!/usr/bin/env python3
"""
HTML Report Generator

Generates HTML reports from templates and data.
"""

from pathlib import Path
from typing import Any


class HTMLGenerator:
    """Generates HTML reports from templates."""

    def __init__(self, template_dir: str):
        """
        Initialize HTML generator with template directory.

        Args:
            template_dir: Directory containing HTML templates.
        """
        self.template_dir = Path(template_dir)
        if not self.template_dir.exists():
            raise FileNotFoundError(f"Template directory not found: {template_dir}")

    def load_template(self, template_name: str) -> str:
        """
        Load an HTML template file.

        Args:
            template_name: Name of the template file.

        Returns:
            Template content as string.
        """
        template_path = self.template_dir / template_name
        if not template_path.exists():
            raise FileNotFoundError(f"Template not found: {template_path}")

        return template_path.read_text()

    def render_template(self, template: str, data: dict[str, Any]) -> str:
        """
        Render template with data by replacing placeholders.

        Args:
            template: Template string with {key} placeholders.
            data: Dict of data to fill into template.

        Returns:
            Rendered HTML string.
        """
        result = template
        for key, value in data.items():
            placeholder = f"{{{key}}}"
            result = result.replace(placeholder, str(value))
        return result

    def generate(self, data: dict[str, Any], output_path: str) -> str:
        """
        Generate HTML report from data.

        Args:
            data: Data to include in the report.
            output_path: Path where the HTML file should be written.

        Returns:
            Path to the generated HTML file.
        """
        template_name = data.get("_template", "default.html")
        template = self.load_template(template_name)

        rendered = self.render_template(template, data)

        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered)

        return str(output)


def create_default_template() -> str:
    """Create a basic default HTML template."""
    return """<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #333; }
        .data-row { margin: 10px 0; padding: 10px; border-bottom: 1px solid #eee; }
    </style>
</head>
<body>
    <h1>{title}</h1>
    <div class="content">{content}</div>
</body>
</html>"""


if __name__ == "__main__":
    import tempfile
    import os

    with tempfile.TemporaryDirectory() as tmpdir:
        template_dir = Path(tmpdir) / "templates"
        template_dir.mkdir()

        template = create_default_template()
        (template_dir / "default.html").write_text(template)

        generator = HTMLGenerator(str(template_dir))

        data = {
            "_template": "default.html",
            "title": "Test Report",
            "content": "This is a test report generated by HTMLGenerator."
        }

        output_path = Path(tmpdir) / "report.html"
        result = generator.generate(data, str(output_path))

        print(f"Report generated: {result}")
        print(output_path.read_text())
